### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by aczv** [aczv/demo#1]
# Tasks

- [x] Create a milestone and assign some issues
- [x] Create a new label and assign an issue to it
- [ ] Create two commits and release v0.1
- [ ] Close an issue with a commit message

## Another list

- write some code
- write more code
- commit
